'use strict';

// تولیدشده خودکار از کد ۸۶ قرارداد — نگاشت تابع نوشتنی و پارامترهای هر قرارداد
// antennaDep: قراردادهایی که قبل از نوشتن، رکورد آنتن را در namespace خود query می‌کنند
const CONTRACT_FN = {
  AllocateResource: { fn: 'Allocate', params: ["entityID", "resource", "amount"], antennaDep: false },
  AssignRole: { fn: 'Assign', params: ["userID", "role"], antennaDep: false },
  AuthenticateIoT: { fn: 'Authenticate', params: ["deviceID", "token"], antennaDep: false },
  AuthenticateUser: { fn: 'Authenticate', params: ["userID", "token"], antennaDep: false },
  BalanceLoad: { fn: 'Balance', params: ["networkID", "load"], antennaDep: false },
  ConnectIoT: { fn: 'Connect', params: ["deviceID", "antennaID"], antennaDep: false },
  ConnectUser: { fn: 'Connect', params: ["userID", "antennaID"], antennaDep: false },
  DecryptData: { fn: 'Decrypt', params: ["entityID", "data"], antennaDep: false },
  EncryptData: { fn: 'Encrypt', params: ["entityID", "data"], antennaDep: false },
  LocationBasedAntennaConfig: { fn: 'SetAntennaConfig', params: ["antennaID", "config", "x", "y"], antennaDep: false },
  LocationBasedAssignment: { fn: 'AssignAntenna', params: ["entityID", "antennaID", "x", "y"], antennaDep: true },
  LocationBasedBandwidth: { fn: 'AssignBandwidth', params: ["entityID", "antennaID", "bandwidth", "x", "y"], antennaDep: true },
  LocationBasedChannelAllocation: { fn: 'AllocateChannel', params: ["entityID", "channelID", "x", "y"], antennaDep: false },
  LocationBasedCongestion: { fn: 'RecordCongestion', params: ["entityID", "congestion", "x", "y"], antennaDep: false },
  LocationBasedConnection: { fn: 'ConnectEntity', params: ["entityID", "antennaID", "x", "y"], antennaDep: true },
  LocationBasedCoverage: { fn: 'RecordCoverage', params: ["entityID", "coverage", "x", "y"], antennaDep: false },
  LocationBasedDynamicRouting: { fn: 'SetDynamicRoute', params: ["entityID", "route", "x", "y"], antennaDep: false },
  LocationBasedEnergy: { fn: 'RecordEnergy', params: ["entityID", "energy", "x", "y"], antennaDep: false },
  LocationBasedFault: { fn: 'ReportFault', params: ["entityID", "faultType", "x", "y"], antennaDep: false },
  LocationBasedInterference: { fn: 'RecordInterference', params: ["entityID", "interferenceLevel", "x", "y"], antennaDep: false },
  LocationBasedIoTAuthentication: { fn: 'AuthenticateIoT', params: ["deviceID", "token", "x", "y"], antennaDep: false },
  LocationBasedIoTBandwidth: { fn: 'AllocateIoTBandwidth', params: ["deviceID", "antennaID", "bandwidth", "x", "y"], antennaDep: true },
  LocationBasedIoTConnection: { fn: 'ConnectIoT', params: ["deviceID", "antennaID", "x", "y"], antennaDep: true },
  LocationBasedIoTFault: { fn: 'ReportIoTFault', params: ["deviceID", "faultType", "x", "y"], antennaDep: false },
  LocationBasedIoTRegistration: { fn: 'RegisterIoT', params: ["deviceID", "status", "x", "y"], antennaDep: false },
  LocationBasedIoTResource: { fn: 'AllocateIoTResource', params: ["deviceID", "resourceID", "amount", "x", "y"], antennaDep: false },
  LocationBasedIoTRevocation: { fn: 'RevokeIoT', params: ["deviceID", "status", "x", "y"], antennaDep: false },
  LocationBasedIoTSession: { fn: 'StartIoTSession', params: ["deviceID", "sessionID", "x", "y", "status"], antennaDep: false },
  LocationBasedIoTStatus: { fn: 'UpdateIoTStatus', params: ["deviceID", "status", "x", "y"], antennaDep: false },
  LocationBasedLatency: { fn: 'RecordLatency', params: ["entityID", "latency", "x", "y"], antennaDep: false },
  LocationBasedNetworkHealth: { fn: 'RecordNetworkHealth', params: ["entityID", "healthStatus", "x", "y"], antennaDep: false },
  LocationBasedNetworkLoad: { fn: 'RecordNetworkLoad', params: ["entityID", "load", "x", "y"], antennaDep: false },
  LocationBasedPowerManagement: { fn: 'SetPowerLevel', params: ["entityID", "powerLevel", "x", "y"], antennaDep: false },
  LocationBasedPriority: { fn: 'AssignPriority', params: ["entityID", "priority", "x", "y"], antennaDep: false },
  LocationBasedQoS: { fn: 'AssignQoS', params: ["entityID", "antennaID", "qosLevel", "x", "y"], antennaDep: true },
  LocationBasedResourceAllocation: { fn: 'AllocateResource', params: ["entityID", "resourceID", "amount", "x", "y"], antennaDep: false },
  LocationBasedRoaming: { fn: 'PerformRoaming', params: ["entityID", "antennaID", "x", "y"], antennaDep: true },
  LocationBasedSessionManagement: { fn: 'ManageSession', params: ["entityID", "sessionID", "x", "y", "status"], antennaDep: false },
  LocationBasedSignalQuality: { fn: 'RecordSignalQuality', params: ["entityID", "signalQuality", "x", "y"], antennaDep: false },
  LocationBasedSignalStrength: { fn: 'RecordSignalStrength', params: ["entityID", "signal", "x", "y"], antennaDep: false },
  LocationBasedStatus: { fn: 'UpdateStatus', params: ["entityID", "status", "x", "y"], antennaDep: false },
  LocationBasedTraffic: { fn: 'RecordTraffic', params: ["entityID", "traffic", "x", "y"], antennaDep: false },
  LocationBasedUserActivity: { fn: 'RecordUserActivity', params: ["userID", "activity", "x", "y"], antennaDep: false },
  LogAccessAudit: { fn: 'Log', params: ["entityID", "action"], antennaDep: false },
  LogAccessControl: { fn: 'Log', params: ["entityID", "action"], antennaDep: false },
  LogAntennaAudit: { fn: 'Log', params: ["antennaID", "action"], antennaDep: false },
  LogComplianceAudit: { fn: 'Log', params: ["entityID", "complianceStatus"], antennaDep: false },
  LogConnectionAudit: { fn: 'Log', params: ["entityID", "antennaID", "action"], antennaDep: false },
  LogFault: { fn: 'LogFault', params: ["entityID", "faultType"], antennaDep: false },
  LogInterference: { fn: 'LogInterference', params: ["entityID", "interferenceLevel"], antennaDep: false },
  LogIoTActivity: { fn: 'Log', params: ["deviceID", "activity"], antennaDep: false },
  LogIoTAudit: { fn: 'Log', params: ["deviceID", "action"], antennaDep: false },
  LogNetworkAudit: { fn: 'Log', params: ["networkID", "action"], antennaDep: false },
  LogNetworkPerformance: { fn: 'Log', params: ["networkID", "metric", "value"], antennaDep: false },
  LogPerformance: { fn: 'LogPerformance', params: ["entityID", "metric", "value"], antennaDep: false },
  LogPerformanceAudit: { fn: 'Log', params: ["entityID", "metric", "value"], antennaDep: false },
  LogPolicyAudit: { fn: 'Log', params: ["policyID", "action"], antennaDep: false },
  LogPolicyChange: { fn: 'Log', params: ["policyID", "change"], antennaDep: false },
  LogResourceAudit: { fn: 'LogResourceAudit', params: ["entityID", "resource", "amount"], antennaDep: false },
  LogSecurityAudit: { fn: 'Log', params: ["entityID", "event"], antennaDep: false },
  LogSecurityEvent: { fn: 'Log', params: ["entityID", "event"], antennaDep: false },
  LogSession: { fn: 'LogSession', params: ["entityID", "sessionID", "status"], antennaDep: false },
  LogSessionAudit: { fn: 'Log', params: ["entityID", "sessionID", "action"], antennaDep: false },
  LogTraffic: { fn: 'LogTraffic', params: ["entityID", "traffic"], antennaDep: false },
  LogUserActivity: { fn: 'Log', params: ["userID", "activity"], antennaDep: false },
  LogUserAudit: { fn: 'Log', params: ["userID", "action"], antennaDep: false },
  ManageAntenna: { fn: 'UpdateAntennaStatus', params: ["antennaID", "status"], antennaDep: false },
  ManageIoTDevice: { fn: 'UpdateDeviceStatus', params: ["deviceID", "status"], antennaDep: false },
  ManageNetwork: { fn: 'UpdateNetworkStatus', params: ["networkID", "status"], antennaDep: false },
  ManageSession: { fn: 'StartSession', params: ["entityID", "sessionID"], antennaDep: false },
  ManageUser: { fn: 'UpdateUserStatus', params: ["userID", "status"], antennaDep: false },
  MonitorInterference: { fn: 'RecordInterference', params: ["networkID", "interferenceLevel"], antennaDep: false },
  MonitorIoT: { fn: 'RecordStatus', params: ["deviceID", "status"], antennaDep: false },
  MonitorNetwork: { fn: 'RecordStatus', params: ["networkID", "status"], antennaDep: false },
  MonitorResourceUsage: { fn: 'RecordUsage', params: ["entityID", "resource", "amount"], antennaDep: false },
  MonitorTraffic: { fn: 'RecordTraffic', params: ["networkID", "traffic"], antennaDep: false },
  OptimizeNetwork: { fn: 'Optimize', params: ["networkID", "strategy"], antennaDep: false },
  RegisterIoT: { fn: 'Register', params: ["deviceID", "status"], antennaDep: false },
  RegisterUser: { fn: 'Register', params: ["userID", "status"], antennaDep: false },
  RevokeIoT: { fn: 'Revoke', params: ["deviceID", "status"], antennaDep: false },
  RevokeUser: { fn: 'Revoke', params: ["userID", "status"], antennaDep: false },
  SecureCommunication: { fn: 'Establish', params: ["entityID", "channelID"], antennaDep: false },
  SetPolicy: { fn: 'Set', params: ["policyID", "policy"], antennaDep: false },
  UpdatePolicy: { fn: 'Update', params: ["policyID", "policy"], antennaDep: false },
};

module.exports = { CONTRACT_FN };
