name: 6g-fabric-network
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
        eventHub: '300'
        eventReg: '300'
      orderer: '300'
organizations:
$(for ((i=1; i<=8; i++)); do
    ORG_NAME="Org${i}"
    echo "  ${ORG_NAME}:"
    echo "    mspid: ${ORG_NAME}MSP"
    echo "    peers:"
    echo "      - peer0.${ORG_NAME,,}.example.com"
    echo "    certificateAuthorities:"
    echo "      - ca.${ORG_NAME,,}.example.com"
done)
peers:
$(for ((i=1; i<=8; i++)); do
    ORG_NAME="Org${i}"
    PEER_PORT=$((7051 + (i-1)*2000))
    echo "  peer0.${ORG_NAME,,}.example.com:"
    echo "    url: grpcs://localhost:${PEER_PORT}"
    echo "    tlsCACerts:"
    echo "      path: /crypto-config/peerOrganizations/${ORG_NAME,,}.example.com/peers/peer0.${ORG_NAME,,}.example.com/tls/ca.crt"
    echo "    grpcOptions:"
    echo "      ssl-target-name-override: peer0.${ORG_NAME,,}.example.com"
done)
certificateAuthorities:
$(for ((i=1; i<=8; i++)); do
    ORG_NAME="Org${i}"
    CA_PORT=$((7054 + (i-1)*1000))
    echo "  ca.${ORG_NAME,,}.example.com:"
    echo "    url: https://localhost:${CA_PORT}"
    echo "    caName: ca-org${i}"
    echo "    tlsCACerts:"
    echo "      path: /crypto-config/peerOrganizations/${ORG_NAME,,}.example.com/ca/ca.${ORG_NAME,,}.example.com-cert.pem"
    echo "    httpOptions:"
    echo "      verify: false"
done)
orderers:
  orderer1.example.com:
    url: grpcs://localhost:7050
    tlsCACerts:
      path: /crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/ca.crt
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
channels:
$(for CHANNEL in NetworkChannel ResourceChannel PerformanceChannel IoTChannel AuthChannel ConnectivityChannel SessionChannel PolicyChannel AuditChannel SecurityChannel DataChannel AnalyticsChannel MonitoringChannel ManagementChannel OptimizationChannel FaultChannel TrafficChannel AccessChannel ComplianceChannel IntegrationChannel; do
    echo "  ${CHANNEL}:"
    echo "    peers:"
$(for ((i=1; i<=8; i++)); do
    ORG_NAME="Org${i}"
    echo "      peer0.${ORG_NAME,,}.example.com:"
    echo "        endorsingPeer: true"
    echo "        chaincodeQuery: true"
    echo "        ledgerQuery: true"
    echo "        eventSource: true"
done)
done)
